; Scopes

[
  (source_file)
  (body)
  (body_expression)
] @local.scope

; Definitions

(package name: (_) @local.definition)
(library_package name: (_) @local.definition)
(namespace name: (_) @local.definition)
(alias_member name: (_) @local.definition)

(part_definition name: (_) @local.definition)
(item_definition name: (_) @local.definition)
(attribute_definition name: (_) @local.definition)
(enumeration_definition name: (_) @local.definition)
(occurrence_definition name: (_) @local.definition)
(port_definition name: (_) @local.definition)
(connection_definition name: (_) @local.definition)
(interface_definition name: (_) @local.definition)
(allocation_definition name: (_) @local.definition)
(flow_definition name: (_) @local.definition)
(metadata_definition name: (_) @local.definition)
(extended_definition name: (_) @local.definition)
(state_definition name: (_) @local.definition)
(constraint_definition name: (_) @local.definition)
(requirement_definition name: (_) @local.definition)
(concern_definition name: (_) @local.definition)
(case_definition name: (_) @local.definition)
(analysis_case_definition name: (_) @local.definition)
(verification_case_definition name: (_) @local.definition)
(use_case_definition name: (_) @local.definition)
(view_definition name: (_) @local.definition)
(viewpoint_definition name: (_) @local.definition)
(rendering_definition name: (_) @local.definition)
(action_definition name: (_) @local.definition)
(calculation_definition name: (_) @local.definition)

(part_usage name: (_) @local.definition)
(item_usage name: (_) @local.definition)
(attribute_usage name: (_) @local.definition)
(reference_usage name: (_) @local.definition)
(enumeration_usage name: (_) @local.definition)
(occurrence_usage name: (_) @local.definition)
(port_usage name: (_) @local.definition)
(connection_usage name: (_) @local.definition)
(interface_usage name: (_) @local.definition)
(allocation_usage name: (_) @local.definition)
(flow_usage name: (_) @local.definition)
(metadata_usage name: (_) @local.definition)
(state_usage name: (_) @local.definition)
(constraint_usage name: (_) @local.definition)
(requirement_usage name: (_) @local.definition)
(concern_usage name: (_) @local.definition)
(case_usage name: (_) @local.definition)
(analysis_case_usage name: (_) @local.definition)
(verification_case_usage name: (_) @local.definition)
(use_case_usage name: (_) @local.definition)
(view_usage name: (_) @local.definition)
(viewpoint_usage name: (_) @local.definition)
(rendering_usage name: (_) @local.definition)
(event_occurrence_usage name: (_) @local.definition)
(subject_usage name: (_) @local.definition)
(actor_usage name: (_) @local.definition)
(stakeholder_usage name: (_) @local.definition)
(action_usage name: (_) @local.definition)
(calculation_usage name: (_) @local.definition)
(for_variable name: (_) @local.definition)

; References

(qualified_name [(identifier) (unrestricted_name)] @local.reference)
